version: '2'
services:

  lb:
    image: russcox/apptest-lb
    build:
      context: lb/
    ports:
      - 80:80
    links:
      - app

  app:
    image: russcox/apptest
    build:
      context: app/
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_NAME=test
      - DB_USER=root
      - DB_PASS=toor
      - DB_PORT=3306
      - DEBUG=express:*
    links:
      - db

  db:
    image: mysql:8
    volumes:
       - mysqldata:/var/lib/mysql
    ports:
       - 3306:3306
    environment:
       - MYSQL_ROOT_PASSWORD=toor
       - MYSQL_DATABASE=test
       - MYSQL_USER=test
       - MYSQL_PASSWORD=test

volumes:
  mysqldata:
