version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:7.10
        environment:
          DB_HOST: localhost
          DB_NAME: test
          DB_USER: root
          DB_PASS: toor
          DB_PORT: 3306
      - image: mysql:8
        environment:
          MYSQL_ROOT_PASSWORD: toor
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: npm install
          command: |
             ls -ltr
             cd app
             pwd
             ls -l
             npm install
      - run:
          name: Run database migration
          command: |
              cd app
              pwd
              ls -l
              # npm install db-migrate
              node_modules/db-migrate/bin/db-migrate up
      - run:
          name: Build image
          command: |
               cd app
               pwd
               docker build -t russcox/apptest .
      - run:
          name: Start app container
          command: |
               docker run -d -p "3000:3000" -e DB_HOST="localhost" russcox/apptest
               docker ps
      - run:
          name: Wait for db
          command: dockerize -wait tcp://172.17.0.1:3000 -timeout 1m
      - run:
          name: Run test
          command: curl --retry 10 --retry-delay 5 -v http://localhost:3000/api/user
