version: 2.0
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run:
          name: Build container images
          command: |
               docker-compose build
      - run:
          name: Test containers and run test db migration
          command: |
               docker-compose up -d db
               docker-compose up -d app lb
      - run:
          name: Push image to registry
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                 docker login -u $dh_user -p $dh_pass
                 docker tag russcox/app russcox/app:${CIRCLE_SHA1}
                 docker tag russcox/app russcox/app:latest
                 docker push russcox/app:${CIRCLE_SHA1}
                 docker push russcox/app:latest
              fi
  deploytest:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Spin up test AWS environment
          command: |
            cd terraform
            terraform init
            terraform workspace select test
            terraform validate
            terraform plan
      - run:
          name: test ephemeral environment
          command: echo "run tests here"
      - run:
          name: Tear down test environment
          command: echo "run teardown here"
  deploy:
    docker:
      - image: garland/aws-cli-docker
    steps:
      - run:
        command:
workflows:
  version: 2
  build-test:
    jobs:
      - build
      - deploytest:
          requires:
            - build
